---
dependencies: []

galaxy_info:
  author: wennjoe
  description: setting yunshop about cronjob and queue
  company: "yunzshop"
  license: ""
  min_ansible_version: 2.4
  galaxy_tags:
    - yunshop_cronjob