- name: Check that you can connect (GET) to a page and it returns a status 200
  uri:
    url: http://{{ domain }}
  register: http_result
- shell: ~/.acme.sh/acme.sh --issue -d {{ domain }} -w {{ webpath }} --force
  when: http_result is success
- name: copy nginx config
  template: src=https.j2 dest=/usr/local/openresty/nginx/conf/vhost/{{ domain }}.conf
- name: general_key
  shell: ~/.acme.sh/acme.sh --install-cert -d {{ domain }} --key-file /usr/local/openresty/nginx/conf/ssl/{{ domain }}.key --fullchain-file /usr/local/openresty/nginx/conf/ssl/{{ domain }}.pem --reloadcmd "systemctl restart nginx"
