- name: restart rsyslog
  service: name=rsyslog state=restarted enabled=yes
- name: restart crond
  service: name=crond state=restarted enabled=yes
- name: restart supervisor
  service: name=supervisord state=restarted enabled=yes
